//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingOrganizer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingOrganizerDBEntities : DbContext
    {
        public MeetingOrganizerDBEntities()
            : base("name=MeetingOrganizerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Meeting> tbl_Meeting { get; set; }
        public virtual DbSet<tbl_MeetingParticipant> tbl_MeetingParticipant { get; set; }
        public virtual DbSet<tbl_Participant> tbl_Participant { get; set; }
    }
}
